### ISSUE TITLE
verify_licenses.py script fails when using python 3.6 or earlier

### ISSUE THREAD

**Issue by nembery** [demisto/dockerfiles#1364]
Default python3 version for Ubuntu 18.04 is still python 3.6.9. Unfortunately, this version cannot build the docker images correctly as the verify_licenses.py script has a check for PY3 and if so found, uses a `text=True` parameter on line 67. The `text` parameter was only introduced in python 3.7, so 3.6 and earlier will fail. 

A simple fix could be to change `text=True` to be `universal_newlines=True`. The text attribute was added as an alias to universal_newlines in the 3.7 release so they are actually functionally equivalent. 

I made that change locally and the build process completes without issue.

**Comment by glicht** [comment]
Thanks for the suggestion. Will add this in.
