### ISSUE TITLE
demisto/pymisp2 package update

### ISSUE THREAD

**Issue by roofdiver** [demisto/dockerfiles#21853]
Hi!

Not sure if this is the right place, but a new version of pymisp was released and the demisto pymisp docker image is not updated. 

current version
pymisp 2.4.170.2

new version
2.4.178

thanks!

**Comment by JudahSchwartz** [comment]
should be solved by https://github.com/demisto/dockerfiles/pull/21878

**Comment by JudahSchwartz** [comment]
New image available `docker pull demisto/pymisp2:2.4.178.80418`

**Comment by roofdiver** [comment]
thank you!!
