### ISSUE TITLE
verify_licenses unable to detect ISC license?

### ISSUE THREAD

**Issue by konraduh** [demisto/dockerfiles#2595]
It would seem that verify_licenses is unable to detect the ISC license of argus-toolbelt / argus-api.
Output from script: 
`Checking license for package: argus-api ...`
`argus-api: found license from pip show: License: ISC`
`FAILURE: argus-api: no approved license found for license: License: ISC`

However, in approved_licenses I see this: 
`"name": "ISC License (ISCL)"`
`"url": "https://opensource.org/licenses/ISC",`
`"regex": "ISC License"`

**Comment by glicht** [comment]
Fixed as part of: https://github.com/demisto/dockerfiles/pull/2594
