### ISSUE TITLE
Create major versions for reference in other docker images

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/dockerfiles#5808]
I'd like to create a python3-arrow docker image, but I don't want to worry about constantly updating it to build on top of the most recent `demisto/python3-deb` image. Can we have things like the demisto core images publish their major versions so I could do something like:
```
FROM demsito/python3-deb:3
```

**Comment by glicht** [comment]
@upstart-swiss you should use the full tag for the base image. This ensures that the build is repeatable and doesn't change over time.

Once your image is contributed to our repo, you won't need to worry about updating the base image as we do this automatically via dependabot. See here for an example: https://github.com/demisto/dockerfiles/pull/5591

**Comment by upstart-swiss** [comment]
👍 
I think this is a weird practice, but I'm happy to contribute in this way.
