### ISSUE TITLE
Docker images are outdated and insecure,...

### ISSUE THREAD

**Issue by bLackCat-79** [demisto/dockerfiles#6236]
Hey,

Have you guys ever did a docker scan on the images that xsoar is running?
They have 1332 vulnerabilities,...

**Comment by glicht** [comment]
@bLackCat-79 I appreciate your concern. Regarding scanning. all of our images are continuously scanned using Prisma Cloud and an additional third-party scanner. We evaluate all critical/high findings and actively work to prevent and mitigate security vulnerabilities. This is also documented here: https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/docker/docker-images-in-demisto/docker-image-security.html

I understand that a support case on a specific old image has been filed. We will address the question via our support process.
