### ISSUE TITLE
Dependent bot doesn't update the correct dockerfile for intezer-sdk

### ISSUE THREAD

**Issue by davidt99** [demisto/dockerfiles#8164]
Hi,
The awesome automatic process of updating intezer-sdk is somewhat broken. The updates are pushed to `demisto/intezer` which is marked as deprecated but not to `demisto/py3-tools` where it's currently deployed.

Examples:
* `demisto/intezer`: [bump to 1.9.1](https://github.com/demisto/dockerfiles/pull/7993)
* `demisto/py3-tools`: the last PR was a [bump to 1.8.3](https://github.com/demisto/dockerfiles/pull/7839)

I can update the images manually but I figured that if there is an automatic process (a very impressive one I must say), it's better to fix it.

**Comment by JudahSchwartz** [comment]
Looks like the issue is when we have too many open dependabot prs, which is the case for the py3-tools image at the moment. I'll push a few of those through so this should be updated
